# Generated by Django 4.2.1 on 2023-05-10 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeBgInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='HomeBgInfo title')),
                ('title_info', models.CharField(max_length=200, verbose_name='HomeBgInfo title_info')),
                ('info', models.CharField(max_length=500, verbose_name='HomeBgInfo Info_text')),
                ('button_name', models.CharField(max_length=50, verbose_name='HomeBgInfo Button')),
            ],
        ),
    ]
