# Generated by Django 4.2.1 on 2023-05-10 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_headbg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_png', models.ImageField(upload_to='images', verbose_name='Icon png')),
                ('title', models.CharField(max_length=20, verbose_name='Icon title')),
            ],
        ),
    ]
