# Generated by Django 4.2.1 on 2023-05-10 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_trendinggames'),
    ]

    operations = [
        migrations.AddField(
            model_name='trendinggames',
            name='about',
            field=models.TextField(default=1, verbose_name='About game'),
            preserve_default=False,
        ),
    ]
