# Generated by Django 4.2.1 on 2023-05-10 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_category_subtitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Title_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub', models.CharField(max_length=50, verbose_name='Title 1 sub')),
                ('title', models.CharField(max_length=50, verbose_name='Title 1 title')),
            ],
        ),
        migrations.CreateModel(
            name='Title_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub', models.CharField(max_length=50, verbose_name='Title 2 sub')),
                ('title', models.CharField(max_length=50, verbose_name='Title 2 title')),
            ],
        ),
        migrations.CreateModel(
            name='Title_3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub', models.CharField(max_length=50, verbose_name='Title 3 sub')),
                ('title', models.CharField(max_length=50, verbose_name='Title 3 title')),
            ],
        ),
        migrations.DeleteModel(
            name='SubTitle',
        ),
    ]
