# Generated by Django 4.2 on 2023-05-10 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_title_1_title_2_title_3_delete_subtitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Food 1 title')),
                ('text_1', models.CharField(max_length=60, verbose_name='Food 1 t_1')),
                ('text_2', models.CharField(max_length=60, verbose_name='Food 1 t_2')),
                ('text_3', models.CharField(max_length=60, verbose_name='Food 1 t_3')),
                ('p', models.CharField(max_length=200, verbose_name='Food 1 p')),
                ('button', models.CharField(max_length=20, verbose_name='Food 1 button')),
            ],
        ),
        migrations.CreateModel(
            name='Food_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Food 2 title')),
                ('text_1', models.CharField(max_length=60, verbose_name='Food 2 t_1')),
                ('text_2', models.CharField(max_length=60, verbose_name='Food 2 t_2')),
                ('text_3', models.CharField(max_length=60, verbose_name='Food 2 t_3')),
                ('button', models.CharField(max_length=20, verbose_name='Food 2 button')),
            ],
        ),
    ]
