# Generated by Django 4.2 on 2023-05-10 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_food_1_food_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_1', models.CharField(max_length=200, verbose_name='Footer text 1')),
                ('text_2', models.CharField(max_length=200, verbose_name='Footer text 2')),
                ('link', models.URLField(verbose_name='Footer URL')),
            ],
        ),
    ]
