# Generated by Django 4.2.1 on 2023-05-10 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_shop_cat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_cat', models.CharField(max_length=30, verbose_name='Game category')),
            ],
        ),
        migrations.AddField(
            model_name='trendinggames',
            name='game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='game_category', to='main.game'),
            preserve_default=False,
        ),
    ]
