# Generated by Django 4.2.1 on 2023-05-10 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_game_trendinggames_game'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trendinggames',
            name='game',
        ),
    ]
