# Generated by Django 4.2.1 on 2023-05-10 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_trendinggames_game'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Game',
        ),
    ]
