# Generated by Django 4.2.1 on 2023-05-10 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_delete_game'),
    ]

    operations = [
        migrations.CreateModel(
            name='G_cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_cat', models.CharField(max_length=30, verbose_name='Games category')),
            ],
        ),
    ]
