# Generated by Django 4.2.1 on 2023-05-10 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_g_cat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='G_cat',
        ),
    ]
