# Generated by Django 4.2.1 on 2023-05-10 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_delete_g_cat'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameCat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat', models.CharField(max_length=50, verbose_name='Game category')),
            ],
        ),
    ]
