# Generated by Django 4.2.1 on 2023-05-10 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_gamecat'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrendingGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images', verbose_name='Trending Games image')),
                ('name', models.CharField(max_length=60, verbose_name='Trending Games name')),
                ('category', models.CharField(max_length=50, verbose_name='Trending Games category')),
                ('old_price', models.PositiveIntegerField(verbose_name='Trending Games old price')),
                ('new_price', models.PositiveIntegerField(verbose_name='Trending Games')),
                ('about', models.TextField(verbose_name='About game')),
                ('tags', models.CharField(max_length=50, verbose_name='TrendingGames tags')),
                ('reviews', models.TextField(verbose_name='TG Reviews')),
                ('gamecat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_cat', to='main.gamecat')),
            ],
        ),
        migrations.DeleteModel(
            name='TrendingGames',
        ),
    ]
