# Generated by Django 4.2.1 on 2023-05-11 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_trendinggame_delete_trendinggames'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub', models.CharField(max_length=50, verbose_name='Contact subtitle')),
                ('title', models.CharField(max_length=50, verbose_name='Contact title')),
                ('p', models.TextField(verbose_name='Contact text')),
                ('address', models.CharField(max_length=200, verbose_name='Contact address')),
                ('phone', models.PositiveIntegerField(verbose_name='Contact phone')),
                ('email', models.EmailField(max_length=254, verbose_name='Contact Email')),
            ],
        ),
    ]
