# Generated by Django 4.2.1 on 2023-05-11 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContackPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, verbose_name='User name')),
                ('usersurname', models.CharField(max_length=100, verbose_name='User surname')),
                ('email', models.EmailField(max_length=254, verbose_name='Usen email')),
                ('subject', models.CharField(max_length=100, verbose_name='User subject')),
                ('message', models.TextField(verbose_name='User text')),
            ],
        ),
    ]
