# Generated by Django 4.2.1 on 2023-05-11 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_rename_username_contackpost_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_item', to='main.trendinggame')),
            ],
        ),
    ]
